# Generated by Django 3.2.6 on 2021-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
